parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    dsnetpl.column.comment.subscriber:
        class: Dsnetpl\DoctrineColumnCommentBundle\EventSubscriber\ColumnCommentSubscriber
        tags:
            - { name: doctrine.event_subscriber }